# Generated by Django 4.1.7 on 2023-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='COD', max_length=30, null=True),
        ),
    ]
