# Generated by Django 4.1.7 on 2023-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_category_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
