# Generated by Django 4.1.7 on 2023-03-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_productimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='sto',
        ),
    ]
