# Generated by Django 4.1.7 on 2023-03-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_quantity_product_sto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sto',
            new_name='stock',
        ),
    ]
