# Generated by Django 4.1.7 on 2023-03-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userprofile_address_userprofile_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad')], max_length=20, null=True),
        ),
    ]
