# Generated by Django 4.1.7 on 2023-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_address_city_alter_userprofile_district_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
