# Generated by Django 4.1.7 on 2023-03-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur')], max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur')], max_length=20, null=True),
        ),
    ]
