# Generated by Django 4.1.7 on 2023-03-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_remove_review_product_review_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
    ]
