# Generated by Django 4.1.7 on 2023-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_review_img_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
