# Generated by Django 4.1.7 on 2023-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_category_image_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
    ]
